### ISSUE TITLE
Cargo build error

### ISSUE THREAD

**Issue by reversebro** [j-hc/pbdecoder-rs#1]
root@exch01:~/protobuf/pbdecoder-rs-master# cargo build
   Compiling pbdecoder v0.1.0 (/root/protobuf/pbdecoder-rs-master)
error[E0432]: unresolved import `protodeck`
 --> src/main.rs:1:5
  |
1 | use protodeck::decode_proto;
  |     ^^^^^^^^^ use of undeclared crate or module `protodeck`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `pbdecoder` due to previous error

**Comment by j-hc** [comment]
oops. fixed now.

**Comment by reversebro** [comment]
Thanks for fast solving sir, now i have a new error 

root@exch01:~/protobuf/pbdecoder-rs-master/target/debug/examples# rustc decode.rs
error[E0432]: unresolved import `pbdecoder`
 --> decode.rs:1:5
  |
1 | use pbdecoder::decode_proto;
  |     ^^^^^^^^^ maybe a missing crate `pbdecoder`?
  |
  = help: consider adding `extern crate pbdecoder` to use the `pbdecoder` crate

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
 --> decode.rs:7:13
  |
7 |     let s = serde_json::to_string(&parts).unwrap();
  |             ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.

**Comment by j-hc** [comment]
you should use cargo
